### ISSUE TITLE
Showing custom fields alongside meta tab

### ISSUE THREAD

**Issue by iedev1** [fabianmichael/kirby-meta#40]
I've struggled quite a bit to add this plugin to my existing site.

Whenever I added custom fields, the "Metadata (SEO)" tab would disappear.

Neither the Kirby docs nor the plugin docs explain the `tabs` option very well (or I just missed it completely!). Regardless, I'm leaving this as a tip for others if they come across the same "issue".

The way to show other fields alongside the plugin's, you need to add another tab. E.g.,
```yml
# site/blueprints/site.yml
tabs:
  default:
    # Your columns / sections, etc
    columns:
      - width: 1/3
        sections:
         # ...
  meta: tabs/meta/site

# site/blueprints/pages/default.yml
tabs:
  default:
    fields:
      some_field:
        label: Some field
        type: text
  meta: tabs/meta/page
```

Thanks for the awesome work!
